#!/bin/sh
set -e

# Create user if missing
if ! id camera-connect >/dev/null 2>&1; then
    useradd --system --home /var/lib/camera-connect --shell /usr/sbin/nologin camera-connect --groups input,audio,video
fi

mkdir -p /var/lib/camera-connect
chown camera-connect:camera-connect /var/lib/camera-connect

mkdir -p /var/spool/camera-connect
chown camera-connect:camera-connect /var/spool/camera-connect

systemctl daemon-reload
systemctl enable camera-connect.service
systemctl restart camera-connect.service

exit 0